"""Initial migration

Revision ID: 0b4c6f2492f6
Revises: 
Create Date: 2024-10-11 16:34:14.259082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4c6f2492f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_students_UserID', table_name='students')
    op.drop_table('students')
    op.drop_index('ix_groups_id', table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_number', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_groups_id', 'groups', ['id'], unique=False)
    op.create_table('students',
    sa.Column('UserID', sa.VARCHAR(), nullable=False),
    sa.Column('Name', sa.VARCHAR(), nullable=False),
    sa.Column('DrexelID', sa.VARCHAR(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_index('ix_students_UserID', 'students', ['UserID'], unique=False)
    # ### end Alembic commands ###
